// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: activation_audit.proto

package ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActivationAudit_Action int32

const (
	ActivationAudit_SEEN           ActivationAudit_Action = 0
	ActivationAudit_ACCEPTED       ActivationAudit_Action = 1
	ActivationAudit_DECLINED       ActivationAudit_Action = 2
	ActivationAudit_PASSED_ON      ActivationAudit_Action = 3
	ActivationAudit_SEEN_CONFIRMED ActivationAudit_Action = 4
)

// Enum value maps for ActivationAudit_Action.
var (
	ActivationAudit_Action_name = map[int32]string{
		0: "SEEN",
		1: "ACCEPTED",
		2: "DECLINED",
		3: "PASSED_ON",
		4: "SEEN_CONFIRMED",
	}
	ActivationAudit_Action_value = map[string]int32{
		"SEEN":           0,
		"ACCEPTED":       1,
		"DECLINED":       2,
		"PASSED_ON":      3,
		"SEEN_CONFIRMED": 4,
	}
)

func (x ActivationAudit_Action) Enum() *ActivationAudit_Action {
	p := new(ActivationAudit_Action)
	*p = x
	return p
}

func (x ActivationAudit_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActivationAudit_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_activation_audit_proto_enumTypes[0].Descriptor()
}

func (ActivationAudit_Action) Type() protoreflect.EnumType {
	return &file_activation_audit_proto_enumTypes[0]
}

func (x ActivationAudit_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActivationAudit_Action.Descriptor instead.
func (ActivationAudit_Action) EnumDescriptor() ([]byte, []int) {
	return file_activation_audit_proto_rawDescGZIP(), []int{0, 0}
}

type ActivationAudit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion    int32                  `protobuf:"varint,1,opt,name=apiVersion,proto3" json:"apiVersion,omitempty"`
	Action        ActivationAudit_Action `protobuf:"varint,3,opt,name=action,proto3,enum=ws.ActivationAudit_Action" json:"action,omitempty"`
	Comment       string                 `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	ActivationIds []int32                `protobuf:"varint,5,rep,packed,name=activationIds,proto3" json:"activationIds,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *ActivationAudit) Reset() {
	*x = ActivationAudit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_activation_audit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivationAudit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivationAudit) ProtoMessage() {}

func (x *ActivationAudit) ProtoReflect() protoreflect.Message {
	mi := &file_activation_audit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivationAudit.ProtoReflect.Descriptor instead.
func (*ActivationAudit) Descriptor() ([]byte, []int) {
	return file_activation_audit_proto_rawDescGZIP(), []int{0}
}

func (x *ActivationAudit) GetApiVersion() int32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *ActivationAudit) GetAction() ActivationAudit_Action {
	if x != nil {
		return x.Action
	}
	return ActivationAudit_SEEN
}

func (x *ActivationAudit) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *ActivationAudit) GetActivationIds() []int32 {
	if x != nil {
		return x.ActivationIds
	}
	return nil
}

func (x *ActivationAudit) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_activation_audit_proto protoreflect.FileDescriptor

var file_activation_audit_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x61, 0x75, 0x64,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x77, 0x73, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x02,
	0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x64, 0x69,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x32, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x77, 0x73, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x24, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x02, 0x74,
	0x73, 0x22, 0x51, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x45, 0x45, 0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x45,
	0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x45, 0x43, 0x4c, 0x49, 0x4e, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x41, 0x53, 0x53, 0x45, 0x44, 0x5f, 0x4f, 0x4e, 0x10, 0x03,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x45, 0x4e, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x52, 0x4d,
	0x45, 0x44, 0x10, 0x04, 0x42, 0x10, 0x5a, 0x0e, 0x6e, 0x69, 0x6b, 0x2d, 0x63, 0x6c, 0x69, 0x2f,
	0x6c, 0x6d, 0x73, 0x2f, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_activation_audit_proto_rawDescOnce sync.Once
	file_activation_audit_proto_rawDescData = file_activation_audit_proto_rawDesc
)

func file_activation_audit_proto_rawDescGZIP() []byte {
	file_activation_audit_proto_rawDescOnce.Do(func() {
		file_activation_audit_proto_rawDescData = protoimpl.X.CompressGZIP(file_activation_audit_proto_rawDescData)
	})
	return file_activation_audit_proto_rawDescData
}

var file_activation_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_activation_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_activation_audit_proto_goTypes = []interface{}{
	(ActivationAudit_Action)(0),   // 0: ws.ActivationAudit.Action
	(*ActivationAudit)(nil),       // 1: ws.ActivationAudit
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_activation_audit_proto_depIdxs = []int32{
	0, // 0: ws.ActivationAudit.action:type_name -> ws.ActivationAudit.Action
	2, // 1: ws.ActivationAudit.ts:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_activation_audit_proto_init() }
func file_activation_audit_proto_init() {
	if File_activation_audit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_activation_audit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivationAudit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_activation_audit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_activation_audit_proto_goTypes,
		DependencyIndexes: file_activation_audit_proto_depIdxs,
		EnumInfos:         file_activation_audit_proto_enumTypes,
		MessageInfos:      file_activation_audit_proto_msgTypes,
	}.Build()
	File_activation_audit_proto = out.File
	file_activation_audit_proto_rawDesc = nil
	file_activation_audit_proto_goTypes = nil
	file_activation_audit_proto_depIdxs = nil
}
