# https://taskfile.dev

version: '3'

tasks:
  win:
    cmds:
      - GOOS=windows GOARCH=386 go build -o nik-cli.exe .
    silent: true
  proto:
    cmds:
      - c:\temp\proto\bin\protoc --go_out=. *.proto --go_opt=paths=source_relative

  proto2:
    cmds:
      - protoc --go_out=.. *.proto --go_opt=paths=source_relative
